spring.application.name=PetCare360

# Connection string
spring.data.mongodb.uri=mongodb+srv://chavarrodiegofernando3_db_user:otfcbISIQOH4CMD1@cluster0.pcr2sx9.mongodb.net/tiendaDB?retryWrites=true&w=majority